spring:
  application:
    name: spring-cloud-eureka-client-1
server:
  port: 9001 # The 0 value means a random port.
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true